GET http://localhost:4646/hello/rose
User-Agent: firefox

###
GET http://localhost:4646/books

###
POST http://localhost:4646/books
Content-Type: application/json

{
  "title": "dfhsdklfshdk",
  "description": "sdhfsdklfhsdlkfhsdlk",
  "price": 15.2,
  "tags": ["science-fiction", "test"]
}

###

PATCH http://localhost:4646/books/621f44500a095b5fa9502caf
Content-Type: application/json

{
  "title": "Titre modifié"
}

###

DELETE http://localhost:4646/books/621f441d0a095b5fa9502cae

###
GET http://localhost:4646/books/621f441d0a095b5fa9502cae

###

POST http://localhost:4646/test

###

GET http://localhost:4646/pantalons?taille=S

###

POST http://localhost:4646/users/token
Content-Type: application/json

{
  "email": "test@mail.com",
  "password": "test"
}

###

GET http://localhost:4646/additionner/3/4

###

GET http://localhost:4646/calculer/3/4
operation: multiplier

###

GET http://localhost:4646/personnes?name=ju


