GET http://localhost:4646/hello/rose
User-Agent: firefox

###
GET http://localhost:4646/books
Authorization: Bearer 

###
POST http://localhost:4646/books
Content-Type: application/json

{
  "title": "dfhsdklfshdk",
  "description": "sdhfsdklfhsdlkfhsdlk",
  "price": 15.2,
  "author": {
    "name": "J.K. Rowling"
  }
}

###

PATCH http://localhost:4646/books/621f474891c775de53558b02
Content-Type: application/json

{
  "authorId": "6220bfb0f50bbc47bb8c535a"
}

###

DELETE http://localhost:4646/books/621f441d0a095b5fa9502cae

###
GET http://localhost:4646/books/621f2cdfcdda0e778cd8f9d4

###

GET http://localhost:4646/authors

###

POST http://localhost:4646/authors
Content-Type: application/json

{
  "name": "J.K. Rowling"
}

###

POST http://localhost:4646/users
Content-Type: application/json

{
  "email": "john2@mail.com",
  "password": "john"
}

###

POST http://localhost:4646/users/token
Content-Type: application/json

{
  "email": "john2@mail.com",
  "password": "john"
}

###

POST http://localhost:4646/test

###

GET http://localhost:4646/pantalons?taille=S

###

POST http://localhost:4646/users/token
Content-Type: application/json

{
  "email": "test@mail.com",
  "password": "test"
}

###

GET http://localhost:4646/additionner/3/4

###

GET http://localhost:4646/calculer/3/4
operation: multiplier

###

GET http://localhost:4646/personnes?name=ju


