GET http://localhost:4646/hello/rose
User-Agent: firefox

###

POST http://localhost:4646/test

###

GET http://localhost:4646/pantalons?taille=S

###

POST http://localhost:4646/users/token
Content-Type: application/json

{
  "email": "test@mail.com",
  "password": "test"
}
